//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models.OracleDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BluecowEntities : DbContext
    {
        public BluecowEntities()
            : base("name=BluecowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PASSENGER> PASSENGERs { get; set; }
        public DbSet<PASSENGER1> PASSENGER1 { get; set; }
        public DbSet<PENDING_CHANGES> PENDING_CHANGES { get; set; }
    }
}
