//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models.OracleDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTApplications_PendingChanges
    {
        public int PAX_ID { get; set; }
        public short SEASON { get; set; }
        public int BOOKING_NO { get; set; }
        public int COMPONENT_NO { get; set; }
        public string FIRST_NAME { get; set; }
        public string FAMILY_NAME { get; set; }
        public string BOOKING_USER_FIELD_1 { get; set; }
        public string BOOKING_USER_FIELD_2 { get; set; }
        public string BOOKING_USER_FIELD_3 { get; set; }
        public string PROD_CODE { get; set; }
        public string TOUR_CODE { get; set; }
        public string COACH { get; set; }
        public Nullable<System.DateTime> DEPARTURE { get; set; }
        public int AGENCY_NO { get; set; }
        public int CONSULT_NO { get; set; }
        public Nullable<int> CONTACT_ACCOUNT_USER_ID { get; set; }
        public string MARKET_ID { get; set; }
    }
}
