//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models.OracleDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBookings_Passenger
    {
        public int PAX_ID { get; set; }
        public string PERSON_TITLE { get; set; }
        public string FAMILY_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> JOURNEYS_CLUB_ID { get; set; }
        public string PSPT_NATIONALITY { get; set; }
        public string PSPT_NO { get; set; }
        public Nullable<System.DateTime> PSPT_ISS_DATE { get; set; }
        public Nullable<System.DateTime> PSPT_EXP_DATE { get; set; }
        public string EMG_NAME { get; set; }
        public string EMG_RELATION { get; set; }
        public string EMG_PHONE_NO { get; set; }
        public string INS_NAME { get; set; }
        public string INS_POLICY_NO { get; set; }
        public string INS_PHONE_NO { get; set; }
        public string PHONE_NO { get; set; }
        public string SPECIAL_NEED { get; set; }
        public string PSPT_BIRTH_PLACE { get; set; }
        public string OTC_PH_COUNTRY { get; set; }
        public string OTC_PH_LOCAL { get; set; }
        public string OTC_EMAIL { get; set; }
        public string EMG_STATUS { get; set; }
        public Nullable<System.DateTime> EMG_DATE { get; set; }
        public string EMG_PH_COUNTRY { get; set; }
        public string EMG_PH_LOCAL { get; set; }
        public string OTC_STATUS { get; set; }
        public Nullable<System.DateTime> OTC_DATE { get; set; }
        public string OTC_SUPPLIED { get; set; }
        public string GIVEN_NAME { get; set; }
        public string EMG_PH_AREA { get; set; }
        public string OTC_PH_AREA { get; set; }
        public string INS_PH_COUNTRY { get; set; }
        public string INS_PH_AREA { get; set; }
        public string INS_PH_LOCAL { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string UNIQUE_STATUS { get; set; }
        public Nullable<int> PRIM_PAX_ID { get; set; }
        public Nullable<short> TOUR_COUNT { get; set; }
        public string JC_STATUS { get; set; }
        public Nullable<System.DateTime> JC_DATE { get; set; }
        public string PSPT_ISS_AUTH { get; set; }
        public string PSN_PHONE { get; set; }
        public string PSN_EMAIL { get; set; }
        public string ADDR_STATUS { get; set; }
        public Nullable<System.DateTime> ADDR_DATE { get; set; }
        public string ADDR_STREET { get; set; }
        public string ADDR_LOCALITY { get; set; }
        public string ADDR_STATE { get; set; }
        public string ADDR_POSTCODE { get; set; }
        public string ADDR_COUNTRY { get; set; }
        public Nullable<System.DateTime> PAX_UPDATE_DATE { get; set; }
        public string PSN_PH_COUNTRY { get; set; }
        public string PSN_PH_LOCAL { get; set; }
    }
}
