//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models.OracleDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSENGER1
    {
        public int PAX_ID { get; set; }
        public string PERSON_TITLE { get; set; }
        public string FAMILY_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> JOURNEYS_CLUB_ID { get; set; }
        public string PSPT_NATIONALITY { get; set; }
        public string PSPT_NO { get; set; }
        public Nullable<System.DateTime> PSPT_ISS_DATE { get; set; }
        public Nullable<System.DateTime> PSPT_EXP_DATE { get; set; }
        public string EMG_NAME { get; set; }
        public string EMG_RELATION { get; set; }
        public string EMG_PHONE_NO { get; set; }
        public string INS_NAME { get; set; }
        public string INS_POLICY_NO { get; set; }
        public string INS_PHONE_NO { get; set; }
        public string PHONE_NO { get; set; }
        public string SPECIAL_NEED { get; set; }
        public string MEDICATION { get; set; }
        public string PSPT_BIRTH_PLACE { get; set; }
        public string OTC_SUPPLIED { get; set; }
        public string OTC_PH_COUNTRY { get; set; }
        public string OTC_PH_LOCAL { get; set; }
        public string OTC_EMAIL { get; set; }
    }
}
